allow:
	sudo chmod 0644 /var/www/html/shopware/config.php
	sudo chmod 0775 /var/www/html/shopware/cache/html
	sudo chmod 0775 /var/www/html/shopware/cache/general
	sudo chmod 0775 /var/www/html/shopware/cache/templates
	sudo chmod 0775 /var/www/html/shopware/cache/proxies
	sudo chmod 0775 /var/www/html/shopware/cache/mpdf/tmp
	sudo chmod 0775 /var/www/html/shopware/cache/mpdf/ttfontdata
	sudo chmod 0775 /var/www/html/shopware/cache/doctrine/filecache
	sudo chmod 0775 /var/www/html/shopware/cache/doctrine/proxies
	sudo chmod 0775 /var/www/html/shopware/cache/doctrine/attributes
	sudo chmod 0775 /var/www/html/shopware/files/documents
	sudo chmod 0775 /var/www/html/shopware/files/downloads
	sudo chmod 0775 /var/www/html/shopware/engine/Library/Mpdf/tmp
	sudo chmod 0775 /var/www/html/shopware/engine/Library/Mpdf/ttfontdata
	sudo chmod 0775 /var/www/html/shopware/engine/Shopware/Plugins/Community
	sudo chmod 0775 /var/www/html/shopware/engine/Shopware/Plugins/Community/Frontend
	sudo chmod 0775 /var/www/html/shopware/engine/Shopware/Plugins/Community/Core
	sudo chmod 0775 /var/www/html/shopware/engine/Shopware/Plugins/Community/Backend
	sudo chmod 0775 /var/www/html/shopware/engine/Shopware/Plugins/Default
	sudo chmod 0775 /var/www/html/shopware/engine/Shopware/Plugins/Default/Frontend
	sudo chmod 0775 /var/www/html/shopware/engine/Shopware/Plugins/Default/Core
	sudo chmod 0775 /var/www/html/shopware/engine/Shopware/Plugins/Default/Backend
	sudo chmod 0775 /var/www/html/shopware/logs
	sudo chmod 0775 /var/www/html/shopware/media/archive
	sudo chmod 0775 /var/www/html/shopware/media/image
	sudo chmod 0775 /var/www/html/shopware/media/image/thumbnail
	sudo chmod 0775 /var/www/html/shopware/media/music
	sudo chmod 0775 /var/www/html/shopware/media/pdf
	sudo chmod 0775 /var/www/html/shopware/media/unknown
	sudo chmod 0775 /var/www/html/shopware/media/video
	sudo chmod 0775 /var/www/html/shopware/media/temp